{% set name = "aws-encryption-sdk" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d5fbf018fc68d6b1cacbe4dd037fd805296c7736a9fe457eb684d053f7f9563

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - boto3 >=1.10.0
    - cryptography >=2.5.0
    - attrs >=17.4.0
    - wrapt >=1.10.11

test:
  imports:
    - aws_encryption_sdk
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aws/aws-encryption-sdk-python
  dev_url: https://github.com/aws/aws-encryption-sdk-python
  doc_url: https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html
  summary: AWS Encryption SDK implementation for Python
  description: |
    The AWS Encryption SDK is a client-side encryption library designed to make it easy for everyone to encrypt and decrypt data using industry standards and best practices. 
    It enables you to focus on the core functionality of your application, rather than on how to best encrypt and decrypt your data. 
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cedriccuypers
